### ISSUE TITLE
Design flavors for more sensible starting points

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-react-checkout#109]
Currently the develop branch design is segmented in Card components which for some reason can only sometimes be closed/minimized. It acts as a one page checkout, but it doesnt quite look like one. It almost feels like the modularity of the code was brought into the design just to show it off more clearly.

This however leaves developers looking to implement a customer specific design with much to remove and adjust in terms of not just styling but also general JSX formatting.

Would it be possible to offer multiple flavors of the checkout, so that developers can pick the most sensible starting point for their customers? Some example styles could be;
- A stepped approach, using something like hash based routing
- A single page approach where the input fields are logically aligned in a vertical manner
- A technical demo of optional modules and available community features

**Comment by wigman** [comment]
@schmengler @progammer-rkt This is something I discussed with @peterschriever and @jesse-deboer in a call.
We had this idea; if we would put all components in a toplevel directory, and reference all other code from there, it would be very simple to create multiple "themes".

/checkout/index.jsx
/checkout/config.js
/checkout/code/api
/checkout/code/context/
/checkout/code/hook/
/checkout/code/...
/checkout/design/index.jsx
/checkout/design/multistep/components/ (with pagination)
/checkout/design/vertical/ (current implementation)
/checkout/design/luma/ (if anyone feels like creating a version with luma-classes/design)

The benefit of this approach would be, that all logic remains in app/code (we already built it like this from the beginning, putting all state and logic in contexts and hooks for this reason), and you can update app/code if newer versions come out (bugfixes included), but your implementation/customizations are mostly done in /checkout/design

What do we think?

**Comment by progammer-rkt** [comment]
@wigman Providing 2 or 3 starting points in terms of UI is something I really looking forward to. I really like the approach you have mentioned above. But, really feel this is something to consider for a future release.

Also, there is an excellent solution from Jisse out there that already allows us to customize checkout like a theme. I think that approach has more potential than this approach. First of all, for each site, we need to fork the repo and set up it in the current approach. But in Jisses approach, it is totally not necessary. Hyva checkout can be in the vendor folder safely and any customization comes inside a customizable module that resides in the `app/code` directory. It will be even more beneficial if we do the customization inside the `app/design` directory itself.

In the above approach too, providing 2 or 3 designs as a starting point is really making sense. So a perfect amalgam of both these approaches is what I am looking forward to.

**Comment by rajeev-k-tomy** [comment]
This is now available in the beta version of the Hyvä React Checkout `2.0-develop`. Hence closing the issue.
