### ISSUE TITLE
Change from react-app-rewired to CRACO

### ISSUE THREAD

**Issue by jesse-deboer** [hyva-themes/magento2-react-checkout#163]
React App Rewired is not being updated anymore, but Create React App is. 

This is the reason why [CRACO](https://github.com/gsoft-inc/craco)  was developed and I think for the future the checkout would benefit from using this:

https://medium.com/gsoft-tech/why-i-built-craco-33ff39f4fc94

**Comment by jesse-deboer** [comment]
Maybe we could even look towards something like [ViteJS](https://vitejs.dev/). This will solve problems like PostCSS8 being not supported by CRA.

I already did the intergration and it's very easy. There is just one issue left with the dev enviroment combined with Preact, it now only works with React. 

What do you think about this @progammer-rkt, is this something to consider?

**Comment by progammer-rkt** [comment]
@jesse-deboer I will checkout these packages soon. We will be going with React App Rewired for the major release. But, surely we can reconsider it.

**Comment by jesse-deboer** [comment]
Sounds good to me, let's go for V1 and look to this after the release! 😄 

I did some work already, got a few small issues, but will fix them later. This also makes `jit` mode and PostCSS8 possible without the need for an extra `npm` command, and it's superrrrrrr quick (just milliseconds for the rebuild)

https://github.com/jesse-deboer/magento2-hyva-checkout/commit/ea1ca5d9250d3348e985c8ffc297ca496d6e71ab

**Comment by jesse-deboer** [comment]
So instead of using CRACO I used ViteJS as a better toolkit compared to Create React App and React App Rewired. 

I think the basic from which ViteJS starts is way better compared to CRA because it also doesn't need something like CRACO to extend it and has a lot of other benefits like HMR build in + PostCSS 8 support.

Here's the PR I made to change to ViteJS: https://github.com/hyva-themes/magento2-hyva-checkout/pull/189

**Comment by rajeev-k-tomy** [comment]
Closing this issue as we consider ViteJS in the next major version of Hyva checkout `2.x`

**Comment by Sebastian-Nielsen** [comment]
> 

Craco is also not being updated anymore. It's getting discountinued too
