### ISSUE TITLE
replace node_modules/postcss-cli/bin/ with the proper commands in package.json

### ISSUE THREAD

**Issue by DanielRuf** [hyva-themes/magento2-react-checkout#170]
It seems you use `node_modules/<package>/bin/` at https://github.com/hyva-themes/magento2-hyva-checkout/blob/main/src/view/frontend/web/css/tailwind/package.json#L21-L22

This can pose some problems:
* issues with different path handling on some (Windows) systems (should normally not happen but Windows uses different directory separators)
* the command could break if the maintainers decide to move the file or rename it (should normally not happen)
* the command is longer than needed, KISS (keep it stupid simple)

The recommended way to execute `node_modules/.bin/<binary>` (defined binary in the `bin` field of `package.json`) is `<binary> <params>`.

So in this case:

```json
    "build": "postcss tailwind-source.css -o tailwind-output.css",
    "minify": "csso tailwind-output.css --output ../styles.css",
```

See also https://github.com/css/csso-cli/blob/master/package.json#L17 and https://github.com/postcss/postcss-cli/blob/master/package.json#L10

**Comment by rajeev-k-tomy** [comment]
This is no longer applicable from 1.1.0 version onwards as we are not relying on such commands.
