### ISSUE TITLE
Update button in email fieldset is clickable after changing email address

### ISSUE THREAD

**Issue by peterjaap** [hyva-themes/magento2-react-checkout#191]
See this video. After changing it to `peterjaap+test@elgentos.nl`, the button shouldn't be clickable anymore until the email address is actually changed again. After a refresh, expected behavior returns again.

https://user-images.githubusercontent.com/431360/136139676-fa871aca-153a-458e-812b-87319aa6a567.mp4

**Comment by progammer-rkt** [comment]
Good catch @peterjaap . I just build a better UI for login section where this issue is also addressed. The PR: #205

**Comment by rajeev-k-tomy** [comment]
Closing this issue as it is fixed already and available in the stable release.
