### ISSUE TITLE
Collapsible cards inconsistent

### ISSUE THREAD

**Issue by peterjaap** [hyva-themes/magento2-react-checkout#199]
Collapsible;

- Email
- Shipping Information

Non-collapsible:
- Shipping Methods
- Payment Methods
- Product Details
- Order Summary

I'd vote to make everything collapsible. However, on mobile, I'd expect at least the Product Details to be collapsed by default.

![image](https://user-images.githubusercontent.com/431360/136180986-428fe56e-7112-4e2c-9da1-8ec6664c3ea5.png)

**Comment by rajeev-k-tomy** [comment]
Closing this issue as it is fixed already and available in the stable release.
