### ISSUE TITLE
Payment Methods & Product Details are in one card

### ISSUE THREAD

**Issue by peterjaap** [hyva-themes/magento2-react-checkout#200]
I would've expected to have Payment Methods and Product Details in separate cards. They are now in the same card;

![image](https://user-images.githubusercontent.com/431360/136181183-2c11d782-cf8e-4a39-aae6-c452d2dad690.png)

**Comment by rajeev-k-tomy** [comment]
Closing this issue as it is fixed already and available in the stable release.
