### ISSUE TITLE
Product Details card shows too much info on mobile

### ISSUE THREAD

**Issue by peterjaap** [hyva-themes/magento2-react-checkout#201]
The Product Details card on mobile shows:

- Thumbnail
- Name
- SKU
- Price
- Qty + input field + update button
- Subtotal (although it's called Total)

![image](https://user-images.githubusercontent.com/431360/136181936-eb2f382c-5718-45b1-b7c1-d4502558c6a7.png)

I would like to see this changed on mobile to:
- Thumbnail
- Name
- Subtotal

![image](https://user-images.githubusercontent.com/431360/136181812-bf577488-7be4-4219-9ad2-42ba55da7445.png)

(or similar, sorry I'm not a frontender :shrug: )

**Comment by rajeev-k-tomy** [comment]
Closing this as it is fixed.
