### ISSUE TITLE
Installation Instructions are not complete

### ISSUE THREAD

**Issue by cdbessig** [hyva-themes/magento2-react-checkout#203]
I have followed the instructions on both a clients staging site and a fresh stock 2.4.3 install and was not able to get it to work in either instance.

For verbosity, the current install instructions in the readme are:

```
1. Install via composer
composer config repositories.hyva-themes/magento2-hyva-checkout git git@github.com:hyva-themes/magento2-hyva-checkout.git
composer require hyva-themes/magento2-hyva-checkout

2. Enable module
bin/magento setup:upgrade

```

In both environments I am left with a page that simple looks like its broken and JS or CSS is not loading:
![hyva-checkout](https://user-images.githubusercontent.com/5340058/136825606-8dbf96df-357c-4296-afb2-2cab69baef05.png)

I feel that maybe the installation instructions or dependencies have changed over time and the documentation has not kept up to date.  Is there any additional commands that need to be ran?  Do I need to do a npm run development anywhere?

To confirm, I have enable the module in the admin panel and cleared the full page cache.  Additionally, I have also done 

```
rm -rf generated
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy -j 4 -f
php bin/magento cache:clean
php bin/magento cache:flush
php bin/magento indexer:reindex
```

All efforts have resulted in the above screenshot and the equivalent in the clients staging site (but with their theme wrapper (porto))

**Comment by rajeev-k-tomy** [comment]
Closing this issue as there are no further inputs. Feel free to re-open the issue if you are getting the same behaviour
