### ISSUE TITLE
Can not develop custom theme

### ISSUE THREAD

**Issue by jv-etailors** [hyva-themes/magento2-react-checkout#206]
I'm trying to develop a custom theme, based in the instructions of https://github.com/hyva-themes/magento2-checkout-example for the 1.0.0-rc2.

In the readme it states:

> Clone it into app/code/Hyva/CheckoutExample
> Enable your module with bin/magento module:enable Hyva_CheckoutExample
> Run setup upgrade with bin/magento setup:upgrade

> Specify payment methods repositories (if any) in app/code/Hyva/CheckoutExample/reactapp/package.json.
> Navigate into app/code/Hyva/CheckoutExample/reactapp.
> Run npm install (do not use yarn)

When I do the `npm install` in the `app/code/Hyva/CheckoutExample/reactapp/` folder I get an error:
```npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../../../../vendor/hyva-themes/magento2-hyva-checkout/src/reactapp/src" as it does not contain a package.json file.
```
The mentioned package.json does exist in the `vendor/hyva-themes/magento2-hyva-checkout/src/reactapp/`. However if I change the reference in my modules package.json file it throws an other error because the components can not be located. Moving the package.json from `vendor/hyva-themes/magento2-hyva-checkout/src/reactapp/` into the `src/` subfolder is also not the solution to the problem.

By copying the subfolders of `vendor/hyva-themes/magento2-hyva-checkout/src/reactapp/src` to my own module and deleting the reference in the package.json from my own module I could do the `npm install`, however, for updating I'd like to only override the necessary files.

**Comment by jv-etailors** [comment]
After reinitialising the `reactapp` folder on my custom module and removing that line from the package.json I can do an npm install, however, I get this error:

```x-special/nautilus-clipboard
copy
file:///home/jeroen/development/magento2/modules/magento2-checkout/app/vendor/hyva-themes/magento2-hyva-checkout/src/reactapp/src/components
file:///home/jeroen/development/magento2/modules/magento2-checkout/app/vendor/hyva-themes/magento2-hyva-checkout/src/reactapp/src/context
file:///home/jeroen/development/magento2/modules/magento2-checkout/app/vendor/hyva-themes/magento2-hyva-checkout/src/reactapp/src/utils
```

This error disappears when I copy the `reactapp/public/`, `reactapp/scripts/` and `reactapp/src/` to my own module.

**Comment by Nesquik** [comment]
Having the same issue. After removing the dependency from the package.json the linter won't compile:

```
Failed to compile.

src/config.js
  Line 1:17:  Unable to resolve path to module '@hyva/react-checkout/utils/env'                 import/no-unresolved
  Line 4:25:  Unable to resolve path to module '@hyva/react-checkout/utils/rootElement'         import/no-unresolved
  Line 5:43:  Unable to resolve path to module '@hyva/react-checkout/utils/localStorageConfig'  import/no-unresolved

src/index.jsx
  Line 5:25:   Unable to resolve path to module '@hyva/react-checkout/utils/rootElement'                  import/no-unresolved
  Line 6:26:   Unable to resolve path to module '@hyva/react-checkout/components/CheckoutForm'            import/no-unresolved
  Line 7:26:   Unable to resolve path to module '@hyva/react-checkout/context/Form/Step/StepProvider'     import/no-unresolved
  Line 8:29:   Unable to resolve path to module '@hyva/react-checkout/context/App/AppDataProvider'        import/no-unresolved
  Line 9:30:   Unable to resolve path to module '@hyva/react-checkout/context/Cart/CartDataProvider'      import/no-unresolved
  Line 10:34:  Unable to resolve path to module '@hyva/react-checkout/context/Form/CheckoutFormProvider'  import/no-unresolved
```

Trying to circumvent the problem via 
```
ESLINT_NO_DEV_ERRORS=true
```

in the .env will produce this instead: 

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
```
and so on.

**Comment by Morgy93** [comment]
We already discussed this in Slack without a proper solution: https://hyva-themes.slack.com/archives/C01C5DBHL64/p1633165269105000

@jv-etailors @Nesquik What OS are you using? I can confirm that it worked on bare Ubuntu 18.04.5 but not within my local docker dev environment. (Which is weird nonetheless)

**Comment by jv-etailors** [comment]
I've updated Node to 15.14.0 and npm to 7.7.6 and the issue is resolved in both the cloned environment (reinacting a Magento folder stucture) and the actual Magento environment.

I'd like to suggest to add these node and npm versions to the minimal requirements for building a checkout theme, as I could not find any version constraints for this.

**Comment by Morgy93** [comment]
Awesome! I can confirm that it works with docker and node 15 just fine. (Latest v16.12.0 works as well for me)

@Nesquik Could you try again using (at least) node 15 and npm 7?

**Comment by Morgy93** [comment]
It's really weird. I tried multiple times now with node v14 but I cannot get it to work.
If using at least node v15 it works flawless.

@rajeev-k-tomy I'd go for `>= v15` in the README. That "does not cause known issues" (as of now).
Current active LTS is v16 anyway. (src https://nodejs.org/en/about/releases/)

**Comment by wigman** [comment]
I thought it would be a good idea to force the version, so I created this PR https://github.com/hyva-themes/magento2-checkout-example/pull/22.

Probably we should/could close this issue when that is merged.
