### ISSUE TITLE
wrong 1.0.0-rc tag

### ISSUE THREAD

**Issue by DanielRuf** [hyva-themes/magento2-react-checkout#214]
It seems you deleted and recreated the branch from the release:

https://github.com/hyva-themes/magento2-hyva-checkout/tree/1.0.0-rc
https://github.com/hyva-themes/magento2-hyva-checkout/tree/refs/tags/1.0.0-rc/src

**Comment by rajeev-k-tomy** [comment]
Closing as the stable releases are out!
