### ISSUE TITLE
Catch exceptions on address edit validation

### ISSUE THREAD

**Issue by gfobe** [hyva-themes/magento2-react-checkout#223]
[Report out of Slack](https://hyva-themes.slack.com/archives/C01C5DBHL64/p1636713558026200).

When I edit an address of customer account in checkout, user view is working correct to show the errors, but I get error messages in the browser console. This is not an intended behaviour. We want to catch these exceptions or do an early return to avoid it.

![image](https://user-images.githubusercontent.com/1615283/141508389-b3851cf4-74a6-425b-88e6-2b95959e1551.png)

**Comment by gfobe** [comment]
Rajeev K Tomy:
> This is not an intended behaviour. It is happening because we are using Yup.validate() method and it throws such error. The file responsible for this is: `src/hook/useFormValidateThenSubmit.js`. The logic in that file can be improved
>
> This block code is repsonsible for showing errors correctly on inputs:
```js
if (isFormSectionTouched && !_isObjEmpty(formSectionErrors)) {
      setErrorMessage(
        prepareFormSectionErrorMessage(
          formId,
          formSectionErrors,
          setFieldTouched
        )
      );
      focusOnFormErrorElement(formId, formSectionErrors);
    }
```
> The following code throws error in console.
```js
const validationRules = YupObject().shape(validationSchema);
    const isValid = await validationRules.validate(formSectionValues);

    if (isValid) {
      await submitHandler();
    }
```
> Wrapping this block code in a try catch would fix the issue you mentioned.
> May be we can do an early return if the first block of code is executed. Probably, we dont need to further do a validation after that.

**Comment by rajeev-k-tomy** [comment]
This issue is fixed. Hence, closing the issue.
