### ISSUE TITLE
Editing country with state-requirement to country without state throws error

### ISSUE THREAD

**Issue by integer-tom** [hyva-themes/magento2-react-checkout#228]
When changing an adress from countries which also require the user to fill out a state (e.g. India, USA) to a country that doesn't have this requirement (Germany etc.) the error message "The region_id does not match the selected country or region" occures. The checkout can still be finished but the adress won't be saved later on.
![editcountry](https://user-images.githubusercontent.com/94903500/143014695-c30b7c07-3fbb-4ade-a729-df48f8cb7bce.gif)

**Comment by rajeev-k-tomy** [comment]
Issue fixed
