### ISSUE TITLE
Translated names are not being used in error message or mandatory field message

### ISSUE THREAD

**Issue by integer-tom** [hyva-themes/magento2-react-checkout#229]
Although there are existing translations for all input fields in the shipping information, these translations won't be used in the error message that is thrown when they aren't filled out. In the direct annotations, only "Street Adress" ("Straße") won't be translated.
![unvollständigeeingaben](https://user-images.githubusercontent.com/94903500/143015831-daef8625-da41-4708-a8ba-60af9283166b.png)

**Comment by rajeev-k-tomy** [comment]
issue fixed
