### ISSUE TITLE
Need Documentation!

### ISSUE THREAD

**Issue by rajeev-k-tomy** [hyva-themes/magento2-react-checkout#23]

**Comment by progammer-rkt** [comment]
You can find documentation here: https://hyva-themes.github.io/magento2-hyva-checkout/

It contains only the basic information as of now. More technical details are in progress. Stay tuned.

**Comment by schmengler** [comment]
To do: add that link to the README :)

**Comment by schmengler** [comment]
To do: document how country configuration is used (see #138 )

**Comment by progammer-rkt** [comment]
Todo: add env configurations in the doc (see #106)
