### ISSUE TITLE
Mini-cart can be opened in checkout

### ISSUE THREAD

**Issue by integer-tom** [hyva-themes/magento2-react-checkout#231]
The mini-cart can still be opened in the checkout upon clicking the cart-symbol on the top-right side. Items can also be deleted from the cart without having a visible change on the checkout (until trying to place the order).

![minicart](https://user-images.githubusercontent.com/94903500/143019768-807ccf01-223f-4001-b033-455b159b6171.png)

**Comment by rajeev-k-tomy** [comment]
This would be considered in a later release.
