### ISSUE TITLE
Following the current docs and recommended way of installation mismatches versions

### ISSUE THREAD

**Issue by peterschriever** [hyva-themes/magento2-react-checkout#238]
For one of our projects I tried installing the most recent release candidate (RC3) by following the docs located at https://hyva-themes.github.io/magento2-hyva-checkout/installation/ using a Hyva theme and finally setting up customization steps in the recommended way, by using the the Magento2 Checkout Example Template.

Doing so I found that the composer commands near the top install version 0.1.0 by default within the vendor folder. This caused the import statements within the Magento2 Checkout Example Template to be unresolved.

I resolved this by manually adjusting my composer version as such;
```json
"hyva-themes/magento2-hyva-checkout": "^1.0.0-rc3",
```

Problem:
Neither the installation documentation nor the hyva-themes/magento2-checkout-example repository readme mention setting up of compatible composer version.

**Comment by jesse-deboer** [comment]
This should be fixed now after the `1.0.0` release, right? @peterschriever @rajeev-k-tomy

**Comment by peterschriever** [comment]
Yep looks good. Getting `^1.0.0` now
