### ISSUE TITLE
Payment Support: Mollie

### ISSUE THREAD

**Issue by BrentRobert** [hyva-themes/magento2-react-checkout#248]
Mollie provides payment methods that are all hosted on their own payment page.

https://github.com/mollie/magento2

Support would be great, as it's one of the most used payment providers in BE/NL.

**Comment by wigman** [comment]
@BrentRobert There is a Mollie integration by @vberthet / Maison Du Net:
https://github.com/MdnAgency/magento2-hyva-checkout-mollie

I would love some feedback on the integration so we can list it under our supported payment methods :)

**Comment by rajeev-k-tomy** [comment]
@wigman We used this module in couple of projects and it works as expected. There are some eslint/prettier problems reported initially when we add this module. I created a pull request for the same to resolve the problem. 

We used credit card payment from mollie so far. I am not sure about other payment methods supported by mollie though.
