### ISSUE TITLE
Compiled JS is loaded twice

### ISSUE THREAD

**Issue by BrentRobert** [hyva-themes/magento2-react-checkout#279]
Hi Rajeev,

The compiled JS of the checkout seems to be loaded twice, resulting in the error I demo'ed you, not being able to click anywhere:

https://github.com/hyva-themes/magento2-react-checkout/blob/95b140e81e726a4c64b2d9f8dc62ce4c86bb0d79/src/view/frontend/layout/hyvareactcheckout_reactcheckout_index.xml#L5
https://github.com/hyva-themes/magento2-react-checkout/blob/95b140e81e726a4c64b2d9f8dc62ce4c86bb0d79/src/view/frontend/layout/hyvareactcheckout_reactcheckout_index.xml#L37

**Comment by rajeev-k-tomy** [comment]
Thank you for reporting the issue. Fix is created and will be available in the next release.
