### ISSUE TITLE
Add @hyva/react-checkout alias

### ISSUE THREAD

**Issue by wigman** [hyva-themes/magento2-react-checkout#284]
To make sure `@hyva-reacht-checkout` dependencies always work, like in payment methods, regardless wheter they are installed directly into a full checkout clone or a CheckoutExample implementation, we should add the alias here too.

We should probably copy the logic from https://github.com/hyva-themes/magento2-checkout-example/blob/master/reactapp/config-overrides.js.

Any thougths on this @rajeev-k-tomy ?

**Comment by rajeev-k-tomy** [comment]
Great idea! Never thought about it. This will reduce lot of work such as keeping separate branches for example template modules as well as for the original repo.
