### ISSUE TITLE
Could not use the “same_as_shipping” option, because the shipping address has not been set.

### ISSUE THREAD

**Issue by skripka-artem** [hyva-themes/magento2-react-checkout#296]
I use
![Снимок экрана 2022-07-17 в 13 13 34](https://user-images.githubusercontent.com/25773952/179393695-69a8ba19-6ce9-4604-a459-ff17d68e3c41.png)
 virtual products in my site 
When i save billing address or place orders i have error
Could not use the “same_as_shipping” option, because the shipping address has not been set.

This problem only virtual products and from Magento new version 2.2.4 it worked fine on the previous version
I think new version magento change validation of some API endpoints

[](url)

**Comment by rajeev-k-tomy** [comment]
Are you on 2.4.4 magento version? or 2.2.4?

**Comment by rajeev-k-tomy** [comment]
@skripka-artem I cannot replicate your issue in a fresh 2.4.4 magento instance with react checkout installed. I added a virtual product to the cart and was able to successfully update the billing address from the checkout page.

Is there something more I need to do in order to replicate your issue?

**Comment by rajeev-k-tomy** [comment]
Closing this as it is communicated via slack it is working fine for @skripka-artem
