### ISSUE TITLE
The current customer isn't authorized. issue after customer logged out and trying to complete checkout as guest

### ISSUE THREAD

**Issue by ilker-capli** [hyva-themes/magento2-react-checkout#310]
Steps to reproduce:

- Login to Magento add address to adress book.
- Add product and go to checkout.
- select shipping address from adres book. after this step hyva-checkout-storage seems like that: 
`{"customer":{"billing_address_id":2,"shipping_address_id":2},"cart":{"is_billing_same_as_shipping":true}}` 

- Then logout and create new cart
- go to checkout again and try to set new shipping address.

**"The current customer isn't authorized."**

**Comment by rajeev-k-tomy** [comment]
Thank you for reporting this issue. This scenario needs to be tested. However, when we logout it is good we flush the `hyva_checkout_storage` as well.

**Comment by ilker-capli** [comment]
> Thank you for reporting this issue. This scenario needs to be tested. However, when we logout it is good we need to flush the `hyva_checkout_storage` as well. I think that is currently missing

This approach fixes the issue as a workaround. But also need to handle expired sessions.
