### ISSUE TITLE
While entering discount code pressing [Enter] triggering PlaceOrder Action [UX - Enhancements]

### ISSUE THREAD

**Issue by ilker-capli** [hyva-themes/magento2-react-checkout#313]
While entering discount code pressing [Enter] triggering PlaceOrder Action.
So, it's a kind of user behavior and expecting Apply to Discount Code, but Placing Order.

**Comment by rajeev-k-tomy** [comment]
This is correct. This needs to be fixed. We need to invalid formik form when there is a data present in the coupon field. I will incorporate this when I get time.
