### ISSUE TITLE
Checkout doesn't fully load

### ISSUE THREAD

**Issue by bacciproductions** [hyva-themes/magento2-react-checkout#316]
Hi! 
I'm likely making a simple mistake along the way but looking for any help or suggestions anyone has.

I'm working in 2.4.3 and loading the following two extensions with composer:
Hyva_GraphqlTokens
Hyva_ReactCheckout

And I'm getting this checkout page:
![hyva-checkout](https://user-images.githubusercontent.com/30486267/195962097-34257489-1d1e-40ce-9039-60c48c4e7139.jpg)

I was in porto but I've disabled porto and switched back to luma with all other non stock extensions disabled. And some stock extensions still disabled.

I originally had all 2.4.3 magento Graphql extensions on but I've tried them off as well and no change. 

I had Magepack bundling on and turned it off.
I've turned off all JS/CS bundling and merging in backend. 

I have no payment methods enabled yet. Checkout was loading prior to Hyva and I could make it to the second page that showed "no payment methods available".

No JS errors in my chrome console. 
No errors in my logs files that specifically point to an error in Hyva Checkout.

I've never used Hyva checkout and I'm hoping I made a simple mistake or maybe I have some other Magento module disabled.

Thanks to anyone who read this far and if I did something absolutely beginning please excuse me. I love working in Magento and I love learning what mistake I made.

**I have these modules enabled** 
Magento_Store
Magento_MediaGallery
Magento_Directory
Magento_AdvancedPricingImportExport
Magento_Theme
Magento_Config
Magento_Backend
Magento_Authorization
Magento_Eav
Magento_Variable
Magento_Search
Magento_Backup
Magento_Customer
Magento_CacheInvalidate
Magento_Indexer
Magento_Cms
Magento_Rule
Magento_Security
Magento_GraphQl
Magento_EavGraphQl
Magento_StoreGraphQl
Magento_CatalogImportExport
Magento_Catalog
Magento_CatalogInventory
Magento_CatalogRule
Magento_Msrp
Magento_CatalogRuleGraphQl
Magento_CatalogSearch
Magento_CatalogUrlRewrite
Magento_CatalogGraphQl
Magento_MediaStorage
Magento_Quote
Magento_SalesSequence
Magento_CheckoutAgreementsGraphQl
Magento_MediaGalleryUi
Magento_CmsGraphQl
Magento_CmsUrlRewrite
Magento_CmsUrlRewriteGraphQl
Magento_CompareListGraphQl
Magento_ComposerRootUpdatePlugin
Magento_User
Magento_Payment
Magento_Sales
Magento_QuoteGraphQl
Magento_Checkout
Magento_Contact
Magento_Cookie
Magento_Cron
Magento_Widget
Magento_Robots
Magento_Integration
Magento_Downloadable
Magento_CustomerGraphQl
Magento_CustomerImportExport
Magento_DataMigrationTool
Magento_Deploy
Magento_Developer
Magento_Bundle
Magento_DirectoryGraphQl
Magento_DownloadableGraphQl
Magento_CustomerDownloadableGraphQl
Magento_ImportExport
Magento_CatalogCustomerGraphQl
Magento_BundleGraphQl
Magento_AdvancedSearch
Magento_Elasticsearch
Magento_Elasticsearch6
Magento_Email
Magento_EncryptionKey
Magento_GiftMessage
Magento_GiftMessageGraphQl
Magento_GoogleAdwords
Magento_GoogleAnalytics
Magento_Ui
Magento_GoogleShoppingAds
Magento_CatalogCmsGraphQl
Magento_PageCache
Magento_GroupedProduct
Magento_GroupedImportExport
Magento_GroupedCatalogInventory
Magento_GroupedProductGraphQl
Magento_DownloadableImportExport
Magento_Captcha
Magento_InstantPurchase
Magento_Inventory
Magento_InventoryAdminUi
Magento_InventoryAdvancedCheckout
Magento_InventoryApi
Magento_InventoryBundleProduct
Magento_InventoryBundleProductAdminUi
Magento_InventoryBundleProductIndexer
Magento_InventoryCatalog
Magento_InventorySales
Magento_InventoryCatalogAdminUi
Magento_InventoryCatalogApi
Magento_InventoryCatalogFrontendUi
Magento_InventoryCatalogSearch
Magento_InventoryCatalogSearchBundleProduct
Magento_InventoryCatalogSearchConfigurableProduct
Magento_ConfigurableProduct
Magento_ConfigurableProductGraphQl
Magento_InventoryConfigurableProduct
Magento_InventoryConfigurableProductIndexer
Magento_InventoryConfiguration
Magento_InventoryConfigurationApi
Magento_InventoryDistanceBasedSourceSelectionApi
Magento_InventoryElasticsearch
Magento_InventoryExportStockApi
Magento_InventoryIndexer
Magento_InventorySalesApi
Magento_InventoryImportExport
Magento_InventorySourceSelectionApi
Magento_InventoryInStorePickupGraphQl
Magento_Shipping
Magento_InventoryInStorePickupQuoteGraphQl
Magento_Multishipping
Magento_Webapi
Magento_InventoryCache
Magento_Reports
Magento_InventoryMultiDimensionalIndexerApi
Magento_InventoryQuoteGraphQl
Magento_InventoryReservations
Magento_InventoryReservationCli
Magento_InventoryReservationsApi
Magento_InventorySalesAdminUi
Magento_CatalogInventoryGraphQl
Magento_InventorySalesFrontendUi
Magento_InventorySetupFixtureGenerator
Magento_InventoryShipping
Magento_InventoryShippingAdminUi
Magento_InventorySourceDeductionApi
Magento_InventorySourceSelection
Magento_InventorySwatchesFrontendUi
Magento_InventoryVisualMerchandiser
Magento_InventoryWishlist
Magento_JwtFrameworkAdapter
Magento_LayeredNavigation
Magento_LoginAsCustomerApi
Magento_LoginAsCustomerGraphQl
Magento_MediaContent
Magento_MediaContentApi
Magento_MediaContentCatalog
Magento_MediaContentCms
Magento_MediaContentSynchronization
Magento_MediaContentSynchronizationApi
Magento_MediaContentSynchronizationCatalog
Magento_MediaContentSynchronizationCms
Magento_MediaGalleryApi
Magento_MediaGalleryCatalog
Magento_MediaGalleryCatalogIntegration
Magento_MediaGalleryCatalogUi
Magento_MediaGalleryCmsUi
Magento_MediaGalleryIntegration
Magento_MediaGalleryMetadata
Magento_MediaGalleryMetadataApi
Magento_MediaGalleryRenditions
Magento_MediaGalleryRenditionsApi
Magento_MediaGallerySynchronization
Magento_MediaGallerySynchronizationApi
Magento_MediaGallerySynchronizationMetadata
Magento_MediaGalleryUiApi
Magento_CatalogWidget
Magento_MessageQueue
Magento_ConfigurableImportExport
Magento_MysqlMq
Magento_Newsletter
Magento_NewsletterGraphQl
Magento_OfflinePayments
Magento_SalesRule
Magento_Sitemap
Magento_PageBuilder
Magento_GraphQlCache
Magento_Vault
Magento_Paypal
Magento_PaypalGraphQl
Magento_Persistent
Magento_ProductAlert
Magento_CheckoutAgreements
Magento_QuoteBundleOptions
Magento_QuoteConfigurableOptions
Magento_InventoryConfigurableProductAdminUi
Magento_ReCaptchaAdminUi
Magento_ReCaptchaCheckout
Magento_ReCaptchaContact
Magento_ReCaptchaCustomer
Magento_ReCaptchaFrontendUi
Magento_ReCaptchaMigration
Magento_ReCaptchaNewsletter
Magento_ReCaptchaPaypal
Magento_ReCaptchaSendFriend
Magento_ReCaptchaUi
Magento_ReCaptchaUser
Magento_ReCaptchaValidation
Magento_ReCaptchaValidationApi
Magento_ReCaptchaVersion2Checkbox
Magento_ReCaptchaVersion2Invisible
Magento_ReCaptchaVersion3Invisible
Magento_ReCaptchaWebapiApi
Magento_ReCaptchaWebapiGraphQl
Magento_ReCaptchaWebapiRest
Magento_ReCaptchaWebapiUi
Magento_RelatedProductGraphQl
Magento_ReleaseNotification
Magento_RequireJs
Magento_Review
Magento_ReviewGraphQl
Magento_Rss
Magento_CatalogRuleConfigurable
Magento_SalesGraphQl
Magento_SalesInventory
Magento_OfflineShipping
Magento_ConfigurableProductSales
Magento_UrlRewrite
Magento_Elasticsearch7
Magento_Securitytxt
Magento_SendFriend
Magento_SendFriendGraphQl
Magento_InventoryGraphQl
Magento_UrlRewriteGraphQl
Magento_Swatches
Magento_SwatchesGraphQl
Magento_SwatchesLayeredNavigation
Magento_Tax
Magento_TaxGraphQl
Magento_TaxImportExport
Magento_AsynchronousOperations
Magento_ThemeGraphQl
Magento_Translation
Magento_CatalogUrlRewriteGraphQl
Magento_Usps
Magento_InventoryConfigurableProductFrontendUi
Magento_PaypalCaptcha
Magento_VaultGraphQl
Magento_Version
Magento_WebapiSecurity
Magento_WeeeGraphQl
Magento_CurrencySymbol
Magento_Wishlist
Magento_WishlistGraphQl
Dotdigitalgroup_ChatGraphQl
Dotdigitalgroup_EmailGraphQl
Hyva_GraphqlTokens
Hyva_ReactCheckout
Klarna_KpGraphQl
PayPal_BraintreeGraphQl

And these disabled (some commented out):
Magento_AdminAnalytics
Magento_AdobeIms
Magento_AdobeImsApi
Magento_AdobeStockAdminUi
Magento_AdobeStockAssetApi
Magento_AdobeStockClient
Magento_AdobeStockClientApi
Magento_AdobeStockImage
Magento_AdobeStockImageApi
Magento_Amqp
Magento_AmqpStore
Magento_AdminNotification
Magento_BundleImportExport
Magento_CatalogPageBuilderAnalytics
Magento_CmsPageBuilderAnalytics
Magento_Csp
Magento_Dhl
Magento_Fedex
Magento_Analytics
Magento_InventoryBundleImportExport
Magento_InventoryDistanceBasedSourceSelection
Magento_InventoryDistanceBasedSourceSelectionAdminUi
Magento_InventoryGroupedProduct
Magento_InventoryGroupedProductAdminUi
Magento_InventoryGroupedProductIndexer
Magento_InventoryInStorePickupApi
Magento_InventoryInStorePickupAdminUi
Magento_InventoryInStorePickup
Magento_InventoryInStorePickupShippingApi
Magento_InventoryInStorePickupSales
Magento_InventoryInStorePickupSalesApi
Magento_InventoryInStorePickupQuote
Magento_InventoryInStorePickupShipping
Magento_InventoryInStorePickupShippingAdminUi
Magento_InventoryLowQuantityNotification
Magento_InventoryLowQuantityNotificationApi
Magento_InventoryProductAlert
Magento_InventoryRequisitionList
Magento_InventoryExportStock
Magento_InventoryInStorePickupFrontend
Magento_LoginAsCustomer
Magento_LoginAsCustomerAdminUi
Magento_LoginAsCustomerAssistance
Magento_LoginAsCustomerFrontendUi
Magento_LoginAsCustomerLog
Magento_LoginAsCustomerPageCache
Magento_LoginAsCustomerQuote
Magento_LoginAsCustomerSales
Magento_Marketplace
Magento_AdobeStockAsset
Magento_AdobeStockImageAdminUi
Magento_MsrpConfigurableProduct
Magento_MsrpGroupedProduct
Magento_InventoryInStorePickupMultishipping
Magento_NewRelicReporting
Magento_PageBuilderAnalytics
Magento_CardinalCommerce
Magento_ProductVideo
Magento_QuoteAnalytics
Magento_QuoteDownloadableLinks
Magento_ReCaptchaReview
Magento_ReCaptchaStorePickup
Magento_RemoteStorage
Magento_InventoryLowQuantityNotificationAdminUi
Magento_ReviewAnalytics
Magento_AwsS3
Magento_PageBuilderAdminAnalytics
Magento_SalesAnalytics
Magento_CustomerAnalytics
Magento_InventoryInStorePickupSalesAdminUi
Magento_AwsS3PageBuilder
Magento_Swagger
Magento_SwaggerWebapi
Magento_SwaggerWebapiAsync
Magento_TwoFactorAuth
Magento_GoogleOptimizer
Magento_Ups
Magento_SampleData
Magento_CatalogAnalytics
Magento_InventoryInStorePickupWebapiExtension
Magento_WebapiAsync
Magento_Weee
Magento_WishlistAnalytics
Advocodo_CartQuantityMultiple
Amazon_Core
Amazon_Login
Amazon_Payment
------
-------
-------
Dotdigitalgroup_Email
Dotdigitalgroup_Chat
Dotdigitalgroup_Sms
------
------
------
------
------
Klarna_Core
Klarna_Ordermanagement
Klarna_Kp
Klarna_Onsitemessaging
------
MageSuite_Magepack
------
------
------
------
------
------
------
------
------
------
------
------
------
------
------
PayPal_Braintree
Smartwave_Core
Smartwave_Dailydeals
Smartwave_Filterproducts
Smartwave_Megamenu
Smartwave_Porto
Smartwave_Socialfeeds
------
Temando_ShippingRemover
Vendor_Migration
Vertex_Tax
Vertex_AddressValidationApi
Vertex_RequestLoggingApi
Vertex_RequestLogging
Vertex_AddressValidation
------
------
------

**Here is my profiler:** I commented out my site urls.
Timer Id	Time	Avg	Cnt	Emalloc	RealMem
cache_frontend_create	0.014995	0.007498	2	1,525,904	0
magento	2.596903	2.596903	1	94,831,544	15,204,352
·  store.resolve	0.023779	0.023779	1	2,847,216	0
·  session_start	0.001229	0.001229	1	42,176	0
·  EVENT:model_load_before	0.001025	0.001025	1	278,136	0
·  routers_match	1.095885	1.095885	1	30,417,232	4,718,592
·  ·  EAV: Magento\Eav\Model\Config::_initEntityTypes	0.000374	0.000374	1	72,040	0
·  ·  EAV: Magento\Eav\Model\Config::getEntityType	0.000617	0.000617	1	45,168	0
·  ·  load_area:frontend.design	0.002226	0.002226	1	61,432	0
·  ·  load_area:frontend.translate	0.001481	0.001481	1	39,400	0
·  ·  EVENT:controller_action_predispatch	0.319802	0.159901	2	14,717,536	2,621,440
·  ·  ·  OBSERVER:customer_visitor	0.002073	0.001037	2	73,560	0
·  ·  ·  OBSERVER:persistent_synchronize	0.002348	0.001174	2	185,200	0
·  ·  ·  OBSERVER:persistent	0.001865	0.000932	2	79,360	0
·  ·  ·  OBSERVER:persistent_quote	0.311286	0.155643	2	14,333,504	2,621,440
·  ·  ·  ·  QUOTE:Magento\Quote\Model\ResourceModel\Quote\Item\Collection::_assignProducts	0.150578	0.150578	1	4,981,616	0
·  ·  ·  ·  ·  EAV: Magento\Eav\Model\Config::getAttribute	0.009587	0.000355	27	638,072	0
·  ·  ·  ·  ·  ·  EAV: Magento\Eav\Model\Config::getEntityType	0.000111	0.000003	32	2,232	0
·  ·  ·  ·  ·  ·  load_by_code	0.003247	0.001623	2	9,576	0
·  ·  ·  ·  ·  EAV:load_collection	0.015429	0.015429	1	554,632	0
·  ·  ·  ·  ·  ·  load_entities	0.009012	0.009012	1	538,912	0
·  ·  ·  ·  ·  ·  load_attributes	0.006215	0.006215	1	5,360	0
·  ·  ·  ·  ·  ·  ·  EAV: Magento\Eav\Model\Config::getAttribute	0.000382	0.000015	25	1,712	0
·  ·  ·  ·  ·  ·  ·  ·  EAV: Magento\Eav\Model\Config::getEntityType	0.000115	0.000005	25	2,216	0
·  ·  ·  ·  ·  ·  ·  EAV: Magento\Eav\Model\Config::getEntityType	0.000131	0.000005	24	1,848	0
·  ·  ·  ·  ·  EVENT:prepare_catalog_product_collection_prices	0.007716	0.007716	1	305,624	0
·  ·  ·  ·  ·  ·  OBSERVER:catalogrule	0.007686	0.007686	1	303,936	0
·  ·  ·  ·  ·  EVENT:sales_quote_item_collection_products_after_load	0.017788	0.017788	1	678,976	0
·  ·  ·  ·  ·  ·  OBSERVER:add_stock_items	0.012333	0.012333	1	524,360	0
·  ·  ·  ·  ·  ·  OBSERVER:inventory_catalog_preload_cache	0.005400	0.005400	1	152,928	0
·  ·  ·  ·  ·  EVENT:sales_quote_item_qty_set_after	0.063798	0.063798	1	2,015,512	0
·  ·  ·  ·  ·  ·  OBSERVER:inventory	0.063767	0.063767	1	2,013,840	0
·  ·  ·  OBSERVER:persistent_customer	0.000330	0.000165	2	14,752	0
·  ·  CONTROLLER_ACTION:checkout_index_index	0.029792	0.029792	1	317,600	0
·  ·  ·  action_body	0.029757	0.029757	1	316,720	0
·  ·  postdispatch	0.017319	0.008660	2	105,688	0
·  ·  ·  EVENT:controller_action_postdispatch	0.017096	0.008548	2	101,976	0
·  ·  ·  ·  OBSERVER:customer_visitor	0.017021	0.008511	2	94,296	0
·  ·  ·  ·  ·  EVENT:clean_cache_by_tags	0.001863	0.001863	1	62,392	0
·  ·  ·  ·  ·  ·  OBSERVER:invalidate_varnish	0.001656	0.001656	1	54,392	0
·  ·  CONTROLLER_ACTION:hyvaReactCheckout_reactcheckout_index	0.493761	0.493761	1	6,888,808	2,097,152
·  ·  ·  action_body	0.493742	0.493742	1	6,887,912	2,097,152
·  ·  ·  ·  EVENT:checkout_allow_guest	0.002223	0.002223	1	71,736	0
·  ·  ·  ·  ·  OBSERVER:checkout_allow_guest	0.002192	0.002192	1	70,168	0
·  ·  ·  ·  LAYOUT	0.479010	0.159670	3	6,501,520	2,097,152
·  ·  ·  ·  ·  layout_load	0.005387	0.005387	1	112,384	0
·  ·  ·  ·  ·  layout_generate_xml	0.006988	0.006988	1	82,984	0
·  ·  ·  ·  ·  layout_generate_blocks	0.465871	0.465871	1	6,292,960	2,097,152
·  ·  ·  ·  ·  ·  Magento\Framework\View\Layout::Magento\Framework\View\Layout::generateElements	0.464185	0.464185	1	6,711,240	2,097,152
·  ·  ·  ·  ·  ·  ·  generate_elements	0.457862	0.457862	1	6,262,520	2,097,152
·  ·  ·  ·  ·  ·  ·  ·  EVENT:core_layout_block_create_after	0.000283	0.000004	75	-22,296	0
·  ·  ·  ·  ·  ·  ·  ·  Magento\Framework\View\Layout::Magento\Framework\View\Layout::generateElements	0.000991	0.000991	1	193,816	0
·  ·  ·  ·  ·  ·  ·  ·  ·  generate_elements	0.000711	0.000711	1	111,320	0
·  ·  ·  ·  ·  EVENT:layout_generate_blocks_after	0.000536	0.000536	1	10,808	0
·  LAYOUT	1.218978	1.218978	1	8,519,536	10,485,760
·  ·  layout_render	1.218962	1.218962	1	8,519,120	10,485,760
·  ·  ·  EVENT:view_block_abstract_to_html_before	0.000277	0.000005	51	-14,200	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-theme/view/frontend/templates/page/js/require_js.phtml	0.001943	0.001943	1	41,376	0
·  ·  ·  EVENT:view_block_abstract_to_html_after	0.000415	0.000008	51	-14,216	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-theme/view/frontend/templates/html/container.phtml	0.003152	0.003152	1	29,424	0
·  ·  ·  ·  EVENT:core_layout_render_element	0.001302	0.000434	3	21,544	0
·  ·  ·  ·  ·  OBSERVER:pagecache	0.001248	0.000416	3	18,736	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-catalog/view/base/templates/js/components.phtml	0.025656	0.025656	1	243,184	0
·  ·  ·  ·  EVENT:core_layout_render_element	0.001827	0.000228	8	6,288	0
·  ·  ·  ·  ·  OBSERVER:pagecache	0.001694	0.000212	8	1,016	0
·  ·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-page-builder/view/frontend/templates/widget_initializer.phtml	0.019502	0.019502	1	222,208	0
·  ·  ·  EVENT:core_layout_render_element	0.011898	0.000159	75	48,360	0
·  ·  ·  ·  OBSERVER:pagecache	0.011071	0.000148	75	4,088	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-theme/view/frontend/templates/js/cookie.phtml	0.000628	0.000628	1	16,576	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-page-builder/view/base/templates/googlemaps.phtml	0.001252	0.001252	1	45,752	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-store/view/frontend/templates/switch/languages.phtml	0.002238	0.002238	1	117,128	2,097,152
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-theme/view/frontend/templates/html/header/logo.phtml	0.001367	0.001367	1	48,504	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-checkout/view/frontend/templates/cart/minicart.phtml	0.007771	0.007771	1	347,984	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-search/view/frontend/templates/form.mini.phtml	0.002737	0.002737	1	56,616	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-theme/view/frontend/templates/html/sections.phtml	0.262134	0.262134	1	2,612,744	4,194,304
·  ·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-theme/view/frontend/templates/html/container.phtml	0.260463	0.130232	2	2,523,856	4,194,304
·  ·  ·  ·  ·  EAV: Magento\Eav\Model\Config::getEntityType	0.000274	0.000005	53	3,896	0
·  ·  ·  ·  ·  EVENT:magento_catalog_api_data_categoryinterface_load_after	0.001570	0.001570	1	38,176	0
·  ·  ·  ·  ·  ·  OBSERVER:legacy_category_load_after	0.001524	0.001524	1	36,344	0
·  ·  ·  ·  ·  ·  ·  after_load	0.001199	0.001199	1	29,856	0
·  ·  ·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-theme/view/frontend/templates/html/topmenu.phtml	0.092505	0.092505	1	849,688	4,194,304
·  ·  ·  ·  ·  ·  EAV:load_collection	0.051862	0.051862	1	1,316,184	0
·  ·  ·  ·  ·  ·  ·  load_entities	0.043149	0.043149	1	1,282,584	0
·  ·  ·  ·  ·  ·  ·  load_attributes	0.008362	0.008362	1	23,424	0
·  ·  ·  ·  ·  ·  REWRITE: Magento\Catalog\Model\Category::getUrl	0.018813	0.000040	471	434,176	0
·  ·  ·  ·  ·  EAV: Magento\Eav\Model\Config::getAttribute	0.000135	0.000010	14	1,584	0
·  ·  ·  ·  ·  EAV:load_collection	0.103782	0.051891	2	2,608,192	0
·  ·  ·  ·  ·  ·  load_entities	0.076526	0.038263	2	2,564,152	0
·  ·  ·  ·  ·  ·  load_attributes	0.026236	0.013118	2	43,608	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-customer/view/frontend/templates/account/authentication-popup.phtml	0.004118	0.004118	1	355,952	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-customer/view/frontend/templates/js/section-config.phtml	0.001360	0.001360	1	44,936	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-page-cache/view/frontend/templates/javascript.phtml	0.000354	0.000354	1	10,264	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/hyva-themes/magento2-react-checkout/src/view/frontend/templates/translation.phtml	0.013369	0.013369	1	13,848	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/hyva-themes/magento2-react-checkout/src/view/frontend/templates/react-container.phtml	0.850484	0.850484	1	3,416,896	2,097,152
·  ·  ·  ·  EVENT:custom_quote_process	0.000925	0.000071	13	9,376	0
·  ·  ·  ·  ·  OBSERVER:persistent	0.000571	0.000044	13	1,256	0
·  ·  ·  ·  EVENT:currency_display_options_forming	0.003135	0.000784	4	99,112	0
·  ·  ·  ·  ·  OBSERVER:magento_currencysymbol_currency_display_options	0.003036	0.000759	4	95,832	0
·  ·  ·  ·  locale/currency	0.579652	0.579652	1	518,512	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-store/view/frontend/templates/switch/stores.phtml	0.001198	0.001198	1	12,888	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/magento/module-catalog/view/frontend/templates/frontend_storage_manager.phtml	0.000691	0.000691	1	20,600	0
·  ·  ·  TEMPLATE: /deleted/deleted/deleted.website.com/vendor/hyva-themes/magento2-react-checkout/src/view/frontend/templates/react-script.phtml	0.001366	0.001366	1	2,672	0

**Comment by rajeev-k-tomy** [comment]
Can you check in the network section of your browser whether a graphql requests is fired and attach the response here?

**Comment by bacciproductions** [comment]
@rajeev-k-tomy thanks so much. Doesn't look like I'm getting the request in my network tab so I'll research this and see if I have something disabled preventing it. 
Thanks again, I really appreciate it!

**Comment by bacciproductions** [comment]
I am getting some additional JS errors in my console and but still no graphql requests in my network tab.

JS errors in console:
render.js:66 Uncaught TypeError: Cannot read properties of null (reading '__k')
    at Oe (render.js:66:6)
    at Object.render (client.mjs:6:4)
    at index.jsx:27:6
    at index.jsx:27:13
    at index.jsx:27:13
Oe @ render.js:66
render @ client.mjs:6
(anonymous) @ index.jsx:27
(anonymous) @ index.jsx:27
(anonymous) @ index.jsx:27

**Comment by aterjung** [comment]
I'm facing the same problem, the reaction script doesn't load at all. Different Magento versions doesn't affect it, I tested at least 2.4.2, 2.4.3, 2.4.4 and 2.4.5.
This bug is introduced by this commit 6e7b2983828dc1056ab53be5b8194b33552ede38 in version 1.1.2
I don't have access to the Hyvä theme itself at the moment, so I can't examine it further, but it looks to me like the react script launches differently when using Hyvä than when using Luma.
Probably this commit dose not fit for both worlds.
