### ISSUE TITLE
Login with account issue

### ISSUE THREAD

**Issue by ennostuurman** [hyva-themes/magento2-react-checkout#319]
Hyva React checkout 1.1.2

Also reproducible on https://demo.hyva.io/hyva/reactcheckout/ (see attached gif).

Steps to reproduce:
1. Save your email address (as a guest)
2. Click on edit
3. Then switch to login with account

Expected result:
You can login with your account

Actual result:
You can't login as the login button remains disabled.

The question is if this is a bug or that we should just hide the login as guest or with account (loginInfoBox) after saving the email address.

![hyva-react-checkout-login-bug](https://user-images.githubusercontent.com/1906257/202506503-f257e1d4-5c19-4c04-aeb8-27bb235ed354.gif)

**Comment by rajeev-k-tomy** [comment]
@ennostuurman Thank you for reporting this problem. This is indeed a UI bug which needs to be fixed. A merge request #325 is created to fix this problem.
