### ISSUE TITLE
Bump version to 1.1.3

### ISSUE THREAD

**Issue by ennostuurman** [hyva-themes/magento2-react-checkout#329]
The React checkout version should be bumped to 1.1.3 to be able to update the React checkout module w/ composer.

The latest [release 1.1.2](https://github.com/hyva-themes/magento2-react-checkout/releases/tag/1.1.2) dates back to September 21, in the meantime multiple changes and fixes have been [merged into the core](https://github.com/hyva-themes/magento2-react-checkout/commits/main).

**Comment by rajeev-k-tomy** [comment]
You are right. I like to add some more improvements also. Let's do a version update in next week. Thanks for the encouragement :)

**Comment by ennostuurman** [comment]
Sounds like a plan, thx @rajeev-k-tomy ;-)

**Comment by rajeev-k-tomy** [comment]
little late.. but we are now on https://github.com/hyva-themes/magento2-react-checkout/releases/tag/1.1.3

**Comment by Nuranto** [comment]
Build fails after upgrading : 
```
Module not found: Error: Can't resolve '@heroicons/react/24/outline' in '/var/www/html/vendor/hyva-themes/magento2-react-checkout/src/reactapp/src/components/common/ToggleBox'
```

When I check heroicons installed lib, I indeed only see `@heroicons/react/outline` and `@heroicons/react/solid` directories, no `@heroicons/react/24`. Am I missing something ?

**Comment by rajeev-k-tomy** [comment]
Removing the `node_modules` directory and perform a fresh install would probably fix your problem @Nuranto
