### ISSUE TITLE
Coupon code validation fails when the code is provided in capital letters.

### ISSUE THREAD

**Issue by rajeev-k-tomy** [hyva-themes/magento2-react-checkout#352]
Coupon code in Magento should work irrespective of the letter case. An example, a coupon code configured like `10off` should work even if the customer provided it like `10OFF`  or `10oFF` etc. 

But currently, the coupon code formik validation fails when the customer provides a coupon code in capital letters. This should be fixed.

**Comment by spyrmp** [comment]
Hello, are there any workarounds available for the problem we encountered today?
