### ISSUE TITLE
ValidationError: State is required (when click place order)

### ISSUE THREAD

**Issue by namnguyenthanhwork** [hyva-themes/magento2-react-checkout#357]
### Shipping infomation form

Some country has state -> `place order` successfully.

<img width="1713" alt="image" src="https://github.com/hyva-themes/magento2-react-checkout/assets/78526193/aea694fa-8957-4339-9e2b-aa1f4427f2eb">

But if country doesn't has state, I can't place order. 

<img width="1728" alt="image" src="https://github.com/hyva-themes/magento2-react-checkout/assets/78526193/ccabfccb-2886-46be-910c-96b8ef2d61ec">

Can everyone help me? Thanks.

I'm using magento2-react-checkout 2.0-develop

**Comment by namnguyenthanhwork** [comment]
In magento, admin can choice state required in store -> config -> general. If country doesn't have state (select option state change to input text)

**Comment by rajeev-k-tomy** [comment]
@namnguyenthanhwork Looks like you figured out it yourself. I am closing this issue now.
