### ISSUE TITLE
Could not use the \"same_as_shipping\" option, because the shipping address has not been set.

### ISSUE THREAD

**Issue by Jihad-orienteed** [hyva-themes/magento2-react-checkout#364]
I got this error after placing an order Could not use the \"same_as_shipping\" option, because the shipping address has not been set.
Steps to reproduce the isse
1. add an dwonloadable product to the cart fro example : [](https://demo.hyva.io/yoga-adventure.html)
2. as soon as  placing an order the error appear and the error because setBillingMutation have a isSameAsShipping flag
![same_as_shipping error](https://github.com/hyva-themes/magento2-react-checkout/assets/130222393/fcc89a81-445d-4059-b1ce-aa7cc92dfb77)
![setBilling contain same as shipping](https://github.com/hyva-themes/magento2-react-checkout/assets/130222393/d1ad5f62-c1d8-4826-9c55-0d2ef60535d6)

**Comment by Man4x** [comment]
Just in case it could help...
When I'm debugging, the isBillingSame constant in the components/PlaceOrder/hooks/useAddressSave is read from localStorage "cart.is_billing_same_as_shipping" key which doesn't exist.
"is_billing_same_as_shipping" actually exists but there's no "cart" key.
![Capture d’écran 2024-05-17 à 14 36 30](https://github.com/hyva-themes/magento2-react-checkout/assets/5763416/b1341dc7-5e2f-4b2e-bb5d-170e8bf6fb74)

**Comment by rajeev-k-tomy** [comment]
@Jihad-orienteed I just tested this with a fresh installation of Magento 2.4.7 and the react checkout version 2.4.7. I could not reproduce the problem. Order is placed successfully.

So this could be a problem with your environment and setup of react checkout.

**Comment by rajeev-k-tomy** [comment]
@Man4x Thank you for reporting this problem. This will be covered in the pull request #373
